### ISSUE TITLE
Tell user when OOMMF is called

### ISSUE THREAD

**Issue by mb1a15** [joommf/oommfc#12]
We should inform user when OOMMF is called. An option could be to write to terminal `OOMMF is called. This may take a while.`

The reason for this is so that user knows when OOMMF is computing something and that user should wait.

**Comment by mb1a15** [comment]
The downside of this is that it would reduce the overall quality of notebook outputs - especially if OOMMF is called multiple times in a single cell.

**Comment by mb1a15** [comment]
Possible solution is to print this message to the Terminal, not the cell output.

**Comment by mb1a15** [comment]
A suggestion on how to implement this: http://stackoverflow.com/questions/30729318/print-into-console-terminal-not-into-cell-output-of-ipython-notebook

The open question is the stdout location on different operating systems.

**Comment by fangohr** [comment]
I would suggest we try a print statement as part of the normal output in the jupyter output cell. 

If we have many repeated calls of OOMMF, then I could imagine that this is either an anomaly of a tutorial/very small micro magnetic system, or a performance problem (as every instantiation of the demag tensor will take some time), and in the latter case it would be good to know about this.

I would also include the name of the subdirectory in which the current OOMMF run takes place in that output messages, so that the users get a better feel for what is happening behind the scenes and on their file system. 

We can refine this later and change from a print statement to logging output (which can be configured to not be reported by the user), or consider moving the output in the terminal if we can't find another good solution.

**Comment by mb1a15** [comment]
Another possibility would be to print this information to the output cell and then delete these messages when OOMMF is done (if possible).

Similar thing with `interact` widget in Jupyter notebook.

**Comment by fangohr** [comment]
Commit 3935351c0f07a946af44532c9ee8e383f79ca8a0  implements printing of execution time, and commit and 045e69e8a55a83b06c5fd1fffe7edf1fb99d040d also prints the start time. We think this is good enough for now.
