### ISSUE TITLE
Rewrite OOMMF class tests

### ISSUE THREAD

**Issue by mb1a15** [joommf/oommfc#14]
At the moment, OOMMF class tests rely on the environment variables that are set on Travis. Because of this, some of the OOMMF tests fail on different machines. They should be rewritten.

**Comment by fangohr** [comment]
I suggest to rename the relevant files so that they do not start with `test_`. As a result, they are not executed automatically if we run `py.test` in a directory higher up. 
To make sure they execute on Travis, we can create an extra test target in the `Makefile` which is only called by the `.travis.yml` file, and thus not by developers testing their local installation.
