### ISSUE TITLE
Bug: visible in plot_slice, but probably reference issue

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#18]
See dev/bugs/issue-18.ipynb

**Comment by mb1a15** [comment]
I think I know what is the problem. When OOMMF simulation is finished, all omf files created by that run are sorted by the creation time and the newest one is taken to update the system. In these tutorials we are running only 10 cells (very fast simulations) and to the operating system it looks like some files are created at the same time because there is not enough resolution in `ctime` value. This is probably Mac (maybe even Windows) specific because I do not have that problem on an Ubuntu machine. The solution would be to sort by the stage value. I avoided this approach because it needs lots of messy string operations, but now it looks like the only solution.

**Comment by marijanbeg** [comment]
Resolved.
