### ISSUE TITLE
Update standard problem 3

### ISSUE THREAD

**Issue by fangohr** [joommf/oommfc#5]
We currently fix the length of the cube, rather than fixing A and Ms. The advantage of this approach is that the cube's size doesn't change, and thus plotting of it (including cross sections ah half heigh) are easier to do. The disadvantage is that it is slightly counterintuitive for a a problem that requires to find the the length L for which the energies of the two configurations are the same. As L is the cube size *expressed in multiples of the exchange length*, this is okay: we are changing the exchange length rather than the cube size to find the solution. 

It might be good to update the text to explain this, though.

(We could also try to write a second version of the code that actually changes the size - if only to see how well we can support this with the init functions that would need to know the cube size. Should start a second issue if we do this.)

**Comment by marijanbeg** [comment]
I agree this is counterintuitive. However, we use this approach because: 

1. This is how the standard problem 3 is defined (https://www.ctcms.nist.gov/~rdm/mumag.org.html):

```
A cube with edge length, L, expressed in units of the intrinsic length scale...
```
2. Standard problem 3 is implemented this way in OOMMF examples.
3. I think that changing this would most probably change the resulting number (at least slightly).
